[book]
authors = ["Roxette Dillon (Lead Developer, CEO, Programmer)"]
language = "en"
multilingual = false
src = "src"
title = "Nylon (.nyl) Documentation"
description = "Full documentation for .nyl and discord.nyl a work in progress programming language."
